source 'https://rubygems.org'
gem "capistrano", '2.15.5'
gem "dogapi", '1.15.0'
gem "hipchat", '1.3.0'
gem "rake", '10.1.1'
gem "sshkit", '1.5.1'
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "3.2.1"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima"