apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "unification.fullname" . }}
  labels:
    app: {{ template "unification.name" . }}
    chart: {{ template "unification.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "unification.name" . }}
      release: {{ .Release.Name | quote }}
  {{- if (.Values.maxUnavailable) }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
    type: RollingUpdate
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "unification.name" . }}
        release: {{ .Release.Name | quote }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        lifecycle:
          preStop:
            exec:
              command:
              - service
              - nginx
              - stop
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: {{ .Values.readinessInitialDelaySeconds }}
          timeoutSeconds: {{ .Values.readinessTimeoutSeconds }}
        resources:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
