{{- if .Values.ingress.enabled -}}
{{- $ingressWebPath := .Values.ingress.webPath -}}
{{- $fullName := include "unification.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: unification
    chart: {{ template "unification.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.webHosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressWebPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: app-port
  {{- end }}
{{- end }}
