{{- if .Values.ingress.enabled -}}
{{- $webFullName :=  "unification.webFullname" . -}}
{{- $ingressWebPath := .Values.ingress.webPath -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "unification.fullname" . }}
  labels:
    app: {{ template "unification.name" . }}
    chart: {{ template "unification.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    traffic-type: external
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.webHosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressWebPath }}
            backend:
              serviceName: {{ $webFullName }}
              servicePort: http
  {{- end }}
{{- end }}
